<a href="https://colab.research.google.com/github/shakib92/Artificial-Intilligence/blob/main/AI_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr)) #type of array
print(arr.ndim) #dimension of arrray
print(arr[2]) #indexing of 1D
print(arr[1] + arr[3])
print(arr[1:5]) #array slicing 1D
print(arr[2: ])
print(arr[ :3])
print(arr[-3:-1]) #negative slicing 1D
print(arr[1:5:2]) #index 1 to 5 and increment 2

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
3
6
[2 3 4 5]
[3 4 5 6]
[1 2 3]
[4 5]
[2 4]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(type(arr2)) #type of array
print(arr2.ndim) #dimension of arrray
print(arr2[0,1]) #indexing 2D
print(arr2[1,2])
print(arr2[1, -2]) #negative indexing 2D
print(arr2[1, 1:2]) #2D array slicing
print(arr2[0:2, 1])
print(arr2[0:2, 0:2])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
2
6
5
[5]
[2 5]
[[1 2]
 [4 5]]


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.ndim) #dimension of arrray
print(arr3[0,1,2]) #indexing 3D

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
6


copy and view

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[2] = 50

print(arr)
print(x)

[ 1  2 50  4  5]
[1 2 3 4 5]


Reshape 1D to 2D array

In [ ]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr5.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


1D to 3D

In [ ]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr5.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


flattening

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


array sorting

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


join

In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


iterating

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


splittng

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]
