<a href="https://colab.research.google.com/github/sadekulhasan/Artificial-Intilligence/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

data = [[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
arr = np.array(data)
arr


array([[1, 2],
       [3, 4]])

In [ ]:
x= torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_ones = torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [ ]:
x_zeros = torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [ ]:
x_rand = torch.rand_like(x, dtype = torch.float)
x_rand

tensor([[0.5480, 0.6371],
        [0.9174, 0.0084]])

In [ ]:
x_randn = torch.randn_like(x, dtype = torch.float)
x_randn

tensor([[-0.3135,  0.1077],
        [-0.4973,  0.6581]])

In [ ]:
rand_tensor = torch.rand(2,3)
rand_tensor

tensor([[0.9889, 0.9602, 0.2280],
        [0.5939, 0.9939, 0.1947]])

In [ ]:
ones_tensor = torch.ones(2,3, dtype = torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
rand_tensor.shape

torch.Size([2, 3])

In [ ]:
ones_tensor.dtype

torch.float32

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
ones_tensor.device

device(type='cpu')

In [ ]:
if torch.cuda.is_available():
  rand_tensor = rand_tensor.to('cuda')

In [ ]:
rand_tensor

tensor([[0.9889, 0.9602, 0.2280],
        [0.5939, 0.9939, 0.1947]])

In [ ]:
rand_tensor.device

device(type='cpu')

In [ ]:
rand_tensor[ :, 1] = 1
rand_tensor

tensor([[0.9889, 1.0000, 0.2280],
        [0.5939, 1.0000, 0.1947]])

In [ ]:
rand_tensor.sum()

tensor(4.0055)

just single value (item()) without tensor

> Indented block



In [ ]:
rand_tensor.sum().item()

4.005459308624268

In [ ]:
t1 = torch.cat([rand_tensor, ones_tensor], dim = 0)
t1

tensor([[0.9889, 1.0000, 0.2280],
        [0.5939, 1.0000, 0.1947],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [ ]:
t1 = torch.cat([rand_tensor, ones_tensor], dim = 1)
t1

tensor([[0.9889, 1.0000, 0.2280, 1.0000, 1.0000, 1.0000],
        [0.5939, 1.0000, 0.1947, 1.0000, 1.0000, 1.0000]])

In [ ]:
rand_tensor.mul(ones_tensor)

tensor([[0.9889, 1.0000, 0.2280],
        [0.5939, 1.0000, 0.1947]])

In [41]:
ones_tensor.matmul(rand_tensor.T)

tensor([[2.2169, 1.7886],
        [2.2169, 1.7886]])

In [42]:
rand_tensor.add(5)

tensor([[5.9889, 6.0000, 5.2280],
        [5.5939, 6.0000, 5.1947]])

In [44]:
rand_tensor.add_(5)

tensor([[5.9889, 6.0000, 5.2280],
        [5.5939, 6.0000, 5.1947]])

In [45]:
n = np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [46]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [47]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [48]:
x = torch.empty(1)
print(x)

tensor([-5.4516e+20])


In [49]:
x.size()

torch.Size([1])

In [51]:
x = torch.empty(2,3)
print(x)

tensor([[3.4108e+20, 3.3137e-41, 4.9388e+21],
        [3.3137e-41, 1.1210e-43, 0.0000e+00]])


In [52]:
torch.empty(2,2,3)

tensor([[[ 4.8046e+21,  3.3137e-41,  4.6437e+21],
         [ 3.3137e-41,  1.4013e-45,  0.0000e+00]],

        [[ 4.8730e+21,  3.3137e-41, -2.8158e-02],
         [ 4.4707e-41,  4.8730e+21,  3.3137e-41]]])

In [53]:
y=x.view(6)
y

tensor([3.4108e+20, 3.3137e-41, 4.9388e+21, 3.3137e-41, 1.1210e-43, 0.0000e+00])

In [54]:
z=x.view(1,-1)
z

tensor([[3.4108e+20, 3.3137e-41, 4.9388e+21, 3.3137e-41, 1.1210e-43, 0.0000e+00]])

In [55]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [56]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [57]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [58]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [59]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [60]:
a[1,1].item()

1.0

In [61]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])

In [62]:
torch.full((4,4),25)

tensor([[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]])